In [6]:
import pandas as pd

In [30]:
url = 'https://raw.githubusercontent.com/intern2grow/sales-data-analysis/main/sales_data.csv'
df = pd.read_csv(url, index_col=0)
print(df.head(5))

               product     category   price  quantity  revenue
date
2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0

What was the total revenue generated by the company over the course of the year?

In [ ]:
What was the total revenue generated by the company over the course of the year

In [9]:
total_revenue = df['revenue'].sum()
total_revenue

758330.0

Which product had the highest revenue? How much revenue did it generate?

In [16]:
max_rev_product = df.groupby(['product'])['revenue'].sum().sort_values(ascending=False).head(1)
max_rev_product

product
Smartphone    434400.0
Name: revenue, dtype: float64

What was the average price of a product sold by the company?

In [19]:
avg_rev_product = df.groupby(['product'])['revenue'].mean().sort_values(ascending=False)
avg_rev_product

product
Laptop        6000.000000
Smartphone    5297.560976
Tablet        2000.000000
Smartwatch    1680.000000
Speaker       1587.200000
Watch         1486.363636
Headphones    1384.615385
Wallet        1100.000000
Coat           965.714286
Sneakers       900.000000
Hoodie         875.000000
Jeans          860.416667
Backpack       850.000000
T-Shirt        528.947368
Name: revenue, dtype: float64

What was the total quantity of products sold by the company?

In [20]:
total_quantity = df['quantity'].sum()
total_quantity

5360.0

Which category had the highest revenue? How much revenue did it generate?

In [21]:
max_rev_category = df.groupby(['category'])['revenue'].sum().sort_values(ascending=False).head(1)
max_rev_category

category
Electronics    516080.0
Name: revenue, dtype: float64

What was the average revenue per sale?

In [23]:
avg_revenue = df['revenue'].mean()
avg_revenue

2060.679347826087

What was the total revenue generated in each quarter of the year? (i.e. Q1, Q2, Q3, Q4)

In [27]:
df.date = pd.to_datetime(df.date)
df['quarter'] = pd.PeriodIndex(df.date, freq='Q')
quarter_buys = df.groupby(['quarter'])['revenue'].sum().sort_values(ascending=False)
quarter_buys

quarter
2022Q3    197680.0
2022Q4    194580.0
2022Q2    183970.0
2022Q1    182100.0
Freq: Q-DEC, Name: revenue, dtype: float64